config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/help', to: 'static_pages#help'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy' # For older browsers without Javascript.
  get '/signup', to: 'users#new'
  get '/wordcounter', to: 'word_counter#update'
  post '/wordcounter', to: 'word_counter#update'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # Generic ledger_base actions, subclasses use it for destroy and undelete.
  resources :ledger_bases, only: [:index, :show, :destroy] do
    member do
      post 'undelete'
    end
  end

  # The usual actions for displaying/editing posts, plus reply and quote and
  # some tree displays.  Also can use ledger_bases API since LedgerPost is a
  # subclass of LedgerBase.
  resources :ledger_posts,
   only: [:new, :create, :index, :show, :edit, :update] do
    member do
      get 'ancestors' # Show a tree of all quotes and up of a given post.
      get 'descendants' # Show a tree of all replies to a given post.
      get 'descentors' # Show a tree of all quotes and replies to a given post.
      get 'quote' # Make a new post quoting a given post.
      get 'quotes' # List all posts quoting a given post.
      get 'reply' # Make a new reply to a given post.
      get 'replies' # List all replies to a given post.
    end
  end
  patch '/ledger_posts', to: 'ledger_posts#update' # For update without an ID.

  # The usual actions for displaying/editing groups.
  resources :ledger_groups, only: [:new, :create, :index, :show, :edit, :update]

  # This just redirects to the Users page for the user.  Mostly so we can
  # automatically render an object by its class.
  resources :ledger_users, only: [:show]

  # Interface for working with generic link objects.
  resources :link_bases, only: [:index, :show, :destroy] do
    member do
      post 'undelete'
      post 'approve'
      post 'unapprove'
      get 'pending' # Show a list of links waiting for approval.
    end
  end

  # For LinkOpinion and LinkMetaOpinion (meta when field :number1 is defined as
  # the ID of the link record being opinionated about), so you can create a new
  # opinion record and edit it before submitting (but not edit it after
  # creation).  Subclass of LinkBase, so it can also do actions in :link_bases.
  resources :link_opinions, only: [:index, :show, :new, :create]
end

app/controllers/ledger_groups_controller.rb
# frozen_string_literal: true

class LedgerGroupsController < LedgerBasesController
  def index
    @pagy, @ledger_objects = pagy(LedgerSubgroup.all)
  end

  def show
    @ledger_object = LedgerSubgroup.find_by(id: params[:id]) # Can be nil.
  end

  # See parent class for generic edit() method.

  # See parent class for generic update() method.

  private

  def sanitised_params # Sanitise the inputs from the submitted form data.
    params.require(:ledger_subgroup).permit(:name, :description)
  end
end

app/views/ledger_groups/_ledger_group.html.erb
<li id="ledger-group-<%= ledger_group.id %>" class="row">
<% if !ledger_group.allowed_to_view?(current_ledger_user) %>
  <div class="col-xs-12 not-allowed-to-view">
    <%= "#{ledger_group.base_s} You don't have permission to view this object." %>
  </div>
<% else %>
  <div class="col-xs-12 col-sm-8 col-md-9 col-lg-10 <%=
    ledger_group.deleted? ? "deleted" : "content" %>">
    <%= link_to "#{ledger_group.type} ##{ledger_group.id}",
      ledger_base_path(ledger_group) %>
    <span class="group-name"><%= ledger_group.name %></span>
    <div class="description-box">
      <%= Kramdown::Document.new(ledger_group.description).to_html.html_safe -%>
    </div>
    <small><%= ledger_group.created_at.getlocal %></small>
  </div>
  <div class="col-xs-12 col-sm-4 col-md-3 col-lg-2">
    <% if ledger_group.role_test?(current_ledger_user, LinkRole::READER) %>
      <% if params[:action] != "show" %>
        <%= # Note that rather than button_to(), which doesn't work with HTML 3
          # (it generates a HTML 5 <button> rather than a <input type="submit">),
          # so use an explicit form and submit button.
          form_with(url: ledger_group_path(ledger_group),
            local: true, method: :get) do |f| %>
            <%= f.submit "Details",
              class: "btn btn-default button-full-width" %>
          <% end %>
        <br>
      <% end %>
      <% if ledger_group.role_test?(current_ledger_user,
        LinkRole::MEMBER_MODERATOR) # Nested test to avoid DB lookups %>


        <%= form_with(url: edit_ledger_group_path(ledger_group),
          local: true, method: :get) do |f| %>
          <%= f.submit "Edit",
            class: "btn btn-success button-full-width" %>
        <% end %>
        <br>
      <% end %>
    <% end %>
    <%= render 'shared/ledger_delete_button',
      { ledger_object: ledger_group } %>
  </div>
<% end %>
</li>

app/views/ledger_groups/_name_description_settings_form.html.erb
<%= form_with(model: @ledger_object, scope: :ledger_subgroup,
  url: ledger_group_path, local: true, class: "form-group") do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
      <div class="description-form-box">
        <%= f.submit "Update Preview", name: "preview",
          class: "btn btn-primary float-right" %>
        <%= Kramdown::Document.new(@ledger_object.description)
          .to_html.html_safe -%>
      </div>

      <%= f.submit yield(:button_text), class: "btn btn-primary button-full-width" %>
<% end %>

app/views/ledger_groups/destroy.html.erb
<h1>LedgerGroups#destroy</h1>
<p>Find me in app/views/ledger_groups/destroy.html.erb</p>

app/views/ledger_groups/edit.html.erb
<% provide(:page_title, 'Edit Group') %>
<% provide(:button_text, 'Save Changes') %>

<h1>Editing Group "<%= @ledger_object.name %>"</h1>

<div class="row">
  <div class="col-xs-12">
    <%= render 'name_description_settings_form' %>
  </div>
</div>

app/views/ledger_groups/index.html.erb
<% provide(:page_title, 'All Ledger Groups') %>

<h1>All Ledger Groups</h1>

<%== pagy_bootstrap_nav(@pagy) %>
<ul class="list-ledger-objects">
<% @ledger_objects.each do |an_object| %>
<%= render 'ledger_groups/ledger_group', { ledger_group: an_object } %>
<% end %>
</ul>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/ledger_groups/show.html.erb
<% provide(:page_title, 'Show Group') %>

<h1>View Group "<%= @ledger_object.name %>"</h1>

<ul class="list-ledger-objects">
<%= render 'ledger_groups/ledger_group', { ledger_group: @ledger_object } %>
</ul>

app/views/ledger_groups/undelete.html.erb
<h1>LedgerGroups#undelete</h1>
<p>Find me in app/views/ledger_groups/undelete.html.erb</p>

app/views/ledger_groups/update.html.erb
<h1>LedgerGroups#update</h1>
<p>Find me in app/views/ledger_groups/update.html.erb</p>