config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/help', to: 'static_pages#help'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy' # For older browsers without Javascript.
  get '/signup', to: 'users#new'
  get '/wordcounter', to: 'word_counter#update'
  post '/wordcounter', to: 'word_counter#update'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # Generic ledger_base actions, subclasses use it for destroy and undelete.
  resources :ledger_bases, only: [:index, :show, :destroy] do
    member do
      post 'undelete'
    end
  end

  # The usual actions for displaying/editing posts, plus reply and quote and
  # some tree displays.  Also can use ledger_bases API since LedgerPost is a
  # subclass of LedgerBase.
  resources :ledger_posts,
   only: [:new, :create, :index, :show, :edit, :update] do
    member do
      get 'ancestors' # Show a tree of all quotes and up of a given post.
      get 'descendants' # Show a tree of all replies to a given post.
      get 'descentors' # Show a tree of all quotes and replies to a given post.
      get 'quote' # Make a new post quoting a given post.
      get 'quotes' # List all posts quoting a given post.
      get 'reply' # Make a new reply to a given post.
      get 'replies' # List all replies to a given post.
    end
  end
  patch '/ledger_posts', to: 'ledger_posts#update' # For update without an ID.

  # The usual actions for displaying/editing groups.
  resources :ledger_groups, only: [:new, :create, :index, :show, :edit, :update]

  # This just redirects to the Users page for the user.  Mostly so we can
  # automatically render an object by its class.
  resources :ledger_users, only: [:show]

  # Interface for working with generic link objects.
  resources :link_bases, only: [:index, :show, :destroy] do
    member do
      post 'undelete'
      post 'approve'
      post 'unapprove'
      get 'pending' # Show a list of links waiting for approval.
    end
  end

  # For LinkOpinion and LinkMetaOpinion (meta when field :number1 is defined as
  # the ID of the link record being opinionated about), so you can create a new
  # opinion record and edit it before submitting (but not edit it after
  # creation).  Subclass of LinkBase, so it can also do actions in :link_bases.
  resources :link_opinions, only: [:index, :show, :new, :create]
end

app/models/user.rb
# frozen_string_literal: true

require_relative "application_record.rb"

class User < ApplicationRecord
  belongs_to :ledger_user, class_name: :LedgerBase, optional: true

  before_save :downcase_email
  before_create :create_activation_digest

  attr_accessor :activation_token, :remember_token, :reset_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email,
    presence: true,
    length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Use password_digest field, defines password & password_confirmation attr.
  has_secure_password

  # Returns the hash digest of the given string, useful for making test users.
  class << self
    def digest(string)
      cost = if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
      BCrypt::Password.create(string, cost: cost)
    end
  end

  # Returns a random token string, 22 safe for URL use characters.
  class << self
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # Remember logins using a persistent cookie value, we just store a digest.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches a particular kind of
  # digest (remember, activation).
  def authenticated?(digest_kind, token)
    digest = send("#{digest_kind}_digest")
    return false if digest.nil?

    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.  Saved cookie will no longer log them in.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.  And adds a bonus link if needed.
  def activate
    return if activated

    update_columns(activated: true, activated_at: Time.zone.now)

    # Add a bonus to the corresponding LedgerUser for e-mail verification done.
    bonus_post = LedgerPost.where(subject: "Bonus for Activation")
      .order(created_at: :asc).first # Get oldest post with that subject.
    return unless bonus_post # No post describing bonus, early seeding?

    luser = create_or_get_ledger_user
    LinkBonusUnique.create!(
      creator_id: 0,
      bonus_user: luser,
      bonus_explanation: bonus_post,
      bonus_points: 10,
      expiry_ceremony: LedgerAwardCeremony.last_ceremony + 52,
      rating_points_spent: 3.0,
      rating_points_boost_parent: 1.0,
      rating_points_boost_child: 2.0,
      approved_parent: true,
      approved_child: true,
      reason: "Bonus for activating #{luser} via e-mail verification.",
    )
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(
      reset_digest: User.digest(reset_token),
      reset_sent_at: Time.zone.now,
    )
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Returns the original version LedgerUser record corresponding to this user,
  # if none then creates one and sets up a new user.  If you know the
  # LedgerUser already exists, then ledger_user() would work and give you the
  # original version more quickly.  Note that the name corresponding to this
  # User record is stored in the latest version of the LedgerUser.
  def create_or_get_ledger_user
    lu = ledger_user
    if lu.nil?
      # Create a new LedgerUser but spend zero points on it, since later on the
      # user becomes their own creator, and would end up spending their own
      # points on themself, which would make their recalculated points not
      # equal their current points.  Root would also have wrong spending.
      lu = LedgerUser.create!(
        creator_id: 0,
        name: name,
        email: email,
        rating_points_spent_creating: 0.0,
        rating_points_boost_self: 0.0,
      )
      self.ledger_user_id = lu.id
      save!
      lu.set_up_new_user # Home group etc.
    else
      lu = lu.original_version
    end
    lu
  end

  # Make sure the corresponding LedgerUser has current e-mail and name.  Throws
  # an exception if there aren't enough points available to create the new
  # version of the LedgerUser record.
  def update_ledger_user_email_name
    luser = create_or_get_ledger_user.latest_version
    return if (luser.name == name) && (luser.email == email)

    new_luser = luser.append_version
    new_luser.name = name
    new_luser.email = email
    new_luser.save!
  end

  private

  # Change email to all lower-case, because database index is case sensitive.
  def downcase_email
    email.downcase!
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :index, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Activation email sent to #{@user.email.inspect}.  " \
        "Look for one with the subject \"Rating Stone Account Activation\"."
      redirect_to(root_url)
    else # Bad inputs.
      render("new") # Ask the user to redo the form.
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    if @user&.destroy
      flash[:success] = "User ##{@user.id} \"#{@user.name}\" deleted."
    else
      flash[:warning] = "No user #{params[:id].inspect} to be deleted."
    end
    redirect_to(users_url)
  end

  def edit
  end

  def index
    @pagy, @users = pagy(User.where(activated: true))
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    return redirect_to(root_url) unless @user.activated

    @pagy, @lposts = pagy(LedgerPost.where(
      creator_id: @user.ledger_user_id,
      deleted: false,
    ).order(:created_at))
  end

  def update
    @user.transaction do # Rollback if update to LedgerUser fails.
      if @user.update(user_params)
        @user.update_ledger_user_email_name # Exception if not enough points.
        flash[:success] = "Profile updated."
        redirect_to(@user)
      else
        render("edit")
      end
    end
  end

  private

  def user_params # Sanitise the inputs from the submitted form data.
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :fancy_labels,
      :preview_opinion,
    )
  end

  # Before filters

  # Confirms we are editing the correct user.  Sets @user as a side effect.
  def correct_user
    @user = User.find(params[:id])
    unless current_user?(@user)
      flash[:danger] = "You were trying to edit a different user!  Start over."
      redirect_to(root_url)
    end
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  ##
  # Returns the Gravatar HTML for the given user.  Or empty string for nil user.
  def gravatar_for(user, size: 80)
    return "" unless user

    gravatar_id  = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(
      gravatar_url,
      alt: "[Gravatar icon for #{user.name}]",
      class: "gravatar",
    )
  end
end

app/views/users/_name_email_password_form.html.erb
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :fancy_labels, "Label Style" %><BR>
      <%= f.select :fancy_labels,
        [["Text labels using words, like Up/Meh/Down, Reply, Quote", 0],
        ["Short text labels, like ^/~/v, R, Q", 1],
        ["Iconic labels, like thumbs up 👍/🤏/👎, thought bubbles 🗩 and quotes “”.", 2]],
        # RELATED: Also update ApplicationHelper::DIRECTION_LABELS.
        class: 'form-control' %><BR>

      <%= f.label :preview_opinion %>
      <%= f.check_box :preview_opinion %>
 
      <%= f.submit yield(:button_text), class: "btn btn-primary form-control" %>
    <% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to gravatar_for(user, size: 50), user %>
  <% if current_user.admin? && !current_user?(user) %>
    <%= form_with(url: user, local: true, method: :delete,
      class: 'deletebutton') do |f| %>
      <%= f.submit "Delete",
        class: "btn btn-danger button-full-width" %>
    <% end %>
  <% end %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<% provide(:page_title, 'Edit User') %>
<% provide(:button_text, 'Save Changes') %>

<h1>Update your Profile</h1>

<% if request.env['HTTPS'] != 'on' # Apache web server HTTPS detection. %>
  <div class="row center">
    <div class="col-md-6 col-md-offset-3">
      <div class="alert alert-warning" role="alert">
        You are accessing this web page without using encryption.
        That means someone could more easily spy on your Internet
        connection, see your changed password, and then pretend to be
        you.  If your web browser is new enough, you may wish to
        switch to the encrypted page.
      </div>

      <a href="<%= edit_user_url.sub(/http:/, 'https:') %>"
       class="btn btn-lg btn-primary">Switch to <strong>secure</strong> Profile Update</a>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'name_email_password_form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="https://gravatar.com/emails" target="_blank" rel="noopener">Change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:page_title, 'All Users') %>

<h1>All Activated Users</h1>

<%== pagy_bootstrap_nav @pagy %>
<ul class="users">
  <%= render @users %>
</ul>
<%== pagy_bootstrap_nav @pagy %>

app/views/users/new.html.erb
<% provide(:page_title, 'Sign Up') %>
<% provide(:button_text, 'Create My Account') %>

<h1>Sign Up</h1>

<% if request.env['HTTPS'] != 'on' # Apache web server HTTPS detection. %>
  <div class="row center">
    <div class="col-md-6 col-md-offset-3">
      <div class="alert alert-warning" role="alert">
        You are accessing this web page without using encryption.
        That means someone could more easily spy on your Internet
        connection, see your new password, and then pretend to be
        you.  If your web browser is new enough, you may wish to
        switch to the encrypted page.  If it's older, this unencrypted
        page lets it still run!
      </div>

      <a href="<%= signup_url.sub(/http:/, 'https:') %>"
       class="btn btn-lg btn-primary">Switch to <strong>secure</strong> Sign Up</a>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'name_email_password_form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:page_title, @user.name) %>

<aside class="col-md-4">
  <section class="user_info">
    <%= gravatar_for @user %>
    <h1><%= @user.name %></h1>
    <% luser = @user.ledger_user # Don't need create_or_get_ledger_user here.
    if luser %>
    <p><%= link_to points_html(luser), ledger_base_path(luser) %><br>
    <%= render 'ledger_bases/timestamp_plain', { ledger_object: luser } %></p>
    <% end %>
  </section>
</aside>
<% if @lposts.any?
  post_count = @lposts.count %>
  <h3><%=
    "#{post_count} Ledger #{'Post'.pluralize(post_count)} by #{@user.name}"
  %></h3>
  <%== pagy_bootstrap_nav @pagy %>
  <br clear="all">
  <ol class="list-ledger-objects">
    <%= render @lposts %>
  </ol>
  <%== pagy_bootstrap_nav @pagy %>
<% end %>