config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/help', to: 'static_pages#help'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy' # For older browsers without Javascript.
  get '/signup', to: 'users#new'
  get '/wordcounter', to: 'word_counter#update'
  post '/wordcounter', to: 'word_counter#update'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # Generic ledger_base actions, subclasses use it for destroy and undelete.
  resources :ledger_bases, only: [:index, :show, :destroy] do
    member do
      post 'undelete'
    end
  end

  # The usual actions for displaying/editing posts, plus reply and quote and
  # some tree displays.  Also can use ledger_bases API since LedgerPost is a
  # subclass of LedgerBase.
  resources :ledger_posts,
   only: [:new, :create, :index, :show, :edit, :update] do
    member do
      get 'ancestors' # Show a tree of all quotes and up of a given post.
      get 'descendants' # Show a tree of all replies to a given post.
      get 'descentors' # Show a tree of all quotes and replies to a given post.
      get 'quote' # Make a new post quoting a given post.
      get 'quotes' # List all posts quoting a given post.
      get 'reply' # Make a new reply to a given post.
      get 'replies' # List all replies to a given post.
    end
  end
  patch '/ledger_posts', to: 'ledger_posts#update' # For update without an ID.

  # The usual actions for displaying/editing groups.
  resources :ledger_groups, only: [:new, :create, :index, :show, :edit, :update]

  # This just redirects to the Users page for the user.  Mostly so we can
  # automatically render an object by its class.
  resources :ledger_users, only: [:show]

  # Interface for working with generic link objects.
  resources :link_bases, only: [:index, :show, :destroy] do
    member do
      post 'undelete'
      post 'approve'
      post 'unapprove'
      get 'pending' # Show a list of links waiting for approval.
    end
  end

  # For LinkOpinion and LinkMetaOpinion (meta when field :number1 is defined as
  # the ID of the link record being opinionated about), so you can create a new
  # opinion record and edit it before submitting (but not edit it after
  # creation).  Subclass of LinkBase, so it can also do actions in :link_bases.
  resources :link_opinions, only: [:index, :show, :new, :create]
end

app/controllers/ledger_posts_controller.rb
# frozen_string_literal: true

class LedgerPostsController < LedgerBasesController
  # See parent classes for generic create, edit, index and other methods.

  ##
  # Show a tree of all quotes of a specified post.
  def ancestors
    @ledger_object = LedgerPost.find(params[:id])
    @pagy, @ledger_objects = pagy(LedgerPost.tree_of_quotes(
      id: @ledger_object.original_version_id,
    ))
  end

  ##
  # Show a tree of all replies to a specified post.
  def descendants
    @ledger_object = LedgerPost.find(params[:id])
    @pagy, @ledger_objects = pagy(LedgerPost.tree_of_replies(
      id: @ledger_object.original_version_id,
    ))
  end

  ##
  # Show a tree of all quotes and replies to a specified post.
  def descentors
    @ledger_object = LedgerPost.find(params[:id])
    @pagy, @ledger_objects = pagy(LedgerPost.tree_of_quotes_and_replies(
      id: @ledger_object.original_version_id,
    ))
  end

  def edit
    if @ledger_object
      @ledger_object.summary_of_changes = "Edited version of #{@ledger_object}."
    end
    super
  end

  ##
  # Make a new quote referencing the specified post.
  def quote
    quote_or_reply(true)
  end

  ##
  # List all quotes of a specified post.
  def quotes
    if params[:id]
      @ledger_object = ledger_class_for_controller.find_by(id: params[:id])
    end
    unless @ledger_object
      flash[:danger] = "Can't find object ##{params[:id]} to show quotes."
      return redirect_back(fallback_location: root_url)
    end
    @pagy, @ledger_objects = pagy(@ledger_object.quotes_good)
  end

  ##
  # Make a new reply referencing the specified post.
  def reply
    quote_or_reply(false)
  end

  ##
  # List all replies to a specified post.
  def replies
    if params[:id]
      @ledger_object = ledger_class_for_controller.find_by(id: params[:id])
    end
    unless @ledger_object
      flash[:danger] = "Can't find object ##{params[:id]} to show replies."
      return redirect_back(fallback_location: root_url)
    end
    @pagy, @ledger_objects = pagy(@ledger_object.replies_good)
  end

  # See parent class for generic show() method.

  ##
  # Handle changes after editing, edit preview, and creating new objects.
  def update
    if @ledger_object.nil? # Editing a new object, create in-memory record.
      @ledger_object = ledger_class_for_controller.new(
        creator_id: current_ledger_user.original_version_id,
        summary_of_changes: "New #{ledger_class_for_controller.name}.",
        rating_direction_self: "U",
      )
    end
    unless params.key?(:ledger_post_fields) && # First time, no group field yet.
        params[:ledger_post_fields].key?(:new_groups)
      # Make a home group link for the new object back to its creator's group.
      home_group = current_ledger_user.home_group
      if home_group
        @ledger_object.new_groups << {
          ID: home_group.original_version_id,
          UMD: "U",
          Points: LinkBase::DEFAULT_SPEND_FOR_LINK,
        }
      end
    end
    super
  end

  private

  ##
  # Appends extra dummy spots to the side load attributes of a given object,
  # for new groups, replies and quotes.  These show up in the form as extra
  # fields that let the user fill in the dummy info (has zero points and
  # zero ID so will get ignored unless changed) to add new groups, replies
  # and quotes.
  def append_dummy_side_load_attributes(new_object)
    new_object.new_groups <<
      { ID: "Group #?", UMD: "U", Points: "Points?" }
    new_object.new_replytos <<
      { ID: "Reply Post #?", UMD: "U", Points: "Points?" }
    new_object.new_quotes <<
      { ID: "Quoted Post #?", UMD: "U", Points: "Points?" }
  end

  ##
  # Returns the Ledger class that's appropriate for this controller to handle.
  # Can be used for creating new objects of the appropriate class.
  # FUTURE: Should preload subclasses here since this is often used just before
  # a database find_by.
  def ledger_class_for_controller
    LedgerPost
  end

  ##
  # Start editing a reply or quote to a given content item.  It's sort of like
  # a new post, but with additional data specifying inherited groups and the
  # link back to the post being replied to.  Set it up and let the user edit it.
  def quote_or_reply(quoting)
    prior_post = LedgerPost.find_by(id: params[:id]) # Can be any version of post.
    unless prior_post
      flash[:danger] = "Can't find object ##{params[:id]} to show " \
        "#{quoting ? "quotes" : "replies"}."
      return redirect_back(fallback_location: root_url)
    end
    new_subject = prior_post.subject
    prefix = "#{quoting ? "Qt:" : "Re:"} "
    new_subject = prefix + new_subject unless new_subject.start_with?(prefix)
    @ledger_object = ledger_class_for_controller.new(
      creator_id: current_ledger_user.original_version_id,
      subject: new_subject,
      content: "Say something about " + prior_post.content,
      summary_of_changes: "#{quoting ? "Quote of" : "Reply to"} #{prior_post}.",
    )

    # Add reply/quote links.  Just start by replying to the original message.
    if quoting
      @ledger_object.new_quotes << {
        ID: prior_post.original_version_id,
        UMD: "U",
        Points: LinkBase::DEFAULT_SPEND_FOR_LINK,
      }
    else
      @ledger_object.new_replytos << {
        ID: prior_post.original_version_id,
        UMD: "U",
        Points: LinkBase::DEFAULT_SPEND_FOR_LINK,
      }
    end

    # Add group links.  Same groups as the original post.
    LinkGroupContent.where(
      content_id: prior_post.original_version_id,
      deleted: false,
    ).each do |a_link|
      @ledger_object.new_groups << {
        ID: a_link.group_id,
        UMD: "U",
        Points: LinkBase::DEFAULT_SPEND_FOR_LINK,
      }
    end
    append_dummy_side_load_attributes(@ledger_object)
    render("edit")
  end

  ##
  # Note that :ledger_post_fields (the container of the fields of the post
  # being updated, and auxiliary arrays inside it) doesn't exist when throwing
  # up the form for a totally new post.
  def sanitised_params # Sanitise the main inputs from the submitted form data.
    return {} unless params.key?(:ledger_post_fields) # New form was requested.

    params.require(:ledger_post_fields)
      .permit(:content, :subject, :summary_of_changes)
  end

  ##
  # Convert form parameters into an array of tuples.  Input is a hash of form
  # parameters, keys being (index digit + "_" + purpose code (ID, UMD, Points)),
  # value being the user's input.  Output is an array of tuples (a Hash with
  # ID, UMD, Points), rejecting ones with ID <= 0, and only keeping the first
  # one where there are duplicate IDs.  Unfortunately wasn't able to get the
  # automatic conversion working for fields with "[]" in the name into arrays.
  def form_to_tuples(form_params)
    array_id = [] # Store the input data in separate arrays.
    array_umd = []
    array_points = []

    # First step - just read in the form info and store in the data arrays.

    form_params.each_pair do |key, value|
      next unless /^[0-9]_.*$/ =~ key # Key is single digit "9_something"

      key_index = key.to_i
      if /^[0-9]_ID$/ =~ key
        array_id[key_index] = value.to_i # Incomprehensible strings become 0.
      elsif /^[0-9]_UMD$/ =~ key && /^[UMD]$/ =~ value
        array_umd[key_index] = value
      elsif /^[0-9]_Points$/ =~ key
        array_points[key_index] = value.to_f
      end
    end

    # Second step - append just the valid (all elements present, not a
    # duplicate ID) data items to the output array.

    known_ids = Set.new # For finding duplicates.
    tuple_array = []
    array_id.each_with_index do |id, index|
      next if id <= 0 || known_ids.include?(id)
      next unless array_umd[index] && array_points[index]

      tuple_array <<
        { ID: id, UMD: array_umd[index], Points: array_points[index] }
      known_ids << id
    end
    tuple_array
  end

  ##
  # For parameters that aren't exactly part of this new_object, side load
  # them into instance variables specific to a LedgerPost.
  def side_load_params(new_object)
    super
    if params && params[:new_groups]
      new_object.new_groups = form_to_tuples(params[:new_groups])
    end
    if params && params[:new_replytos]
      new_object.new_replytos = form_to_tuples(params[:new_replytos])
    end
    if params && params[:new_quotes]
      new_object.new_quotes = form_to_tuples(params[:new_quotes])
    end
    append_dummy_side_load_attributes(new_object)
  end

  # For information that isn't exactly part of this @ledger_object, side save
  # it into related records (create them) specific to the object class.  Returns
  # true if successful.  If it fails, return false with validation error
  # message strings appended to new_object, or just throw an exception.
  def side_save(new_object)
    return false unless super

    # FUTURE: Force load future subclasses of LedgerSubgroup here.
    LedgerFullGroup.name

    # Create some LinkGroupContent records to put the post into some groups.

    new_object.new_groups.each do |group_item|
      group_id = group_item[:ID].to_i # So ID filler text becomes zero.
      points = group_item[:Points].to_f
      next if group_id <= 0 || points <= 0.0

      a_group = LedgerSubgroup.find_by(id: group_id)
      if a_group
        link_group = LinkGroupContent.new(
          group_id: a_group.original_version_id,
          content_id: new_object.original_version_id,
          creator_id: current_ledger_user.original_version_id,
          rating_points_spent: points,
          rating_points_boost_parent: points *
                      (1.0 - LinkBase::LINK_TRANSACTION_FEE_RATE),
          rating_direction_parent: group_item[:UMD],
        )
        unless link_group.save
          new_object.errors.add(
            :base,
            "Failed to make link to Group #{group_id}.",
          )
          link_group.errors.each do |error_key, error_value|
            new_object.errors.add(error_key, error_value)
          end

app/views/ledger_posts/_ledger_just_the_post.html.erb
<% ledger_post.update_current_points
  if !ledger_post.allowed_to_view?(current_ledger_user) %>
    <div class="not-allowed-to-view">
      <%= "#{ledger_post.base_s} You don't have permission to view this object." %>
    </div>
<% else %>
  <% # Deleted post being displayed to an outsider, don't reveal anything.
    if ledger_post.deleted? && !ledger_post.creator_owner?(current_ledger_user) %>
    <div class="post-subject deleted">
      Deleted title not shown.
    </div>
    <div class="description-box">
      Deleted content not shown.
    </div>
  <% # Not hidden from the user, but may be deleted.
  else %>
    <div class="<%= # Subject and content, in red via class "deleted" if deleted.
      ledger_post.deleted? ? "deleted " : "" %>post-subject">
      <%= ledger_post.subject.empty? ? "<No Subject>" : ledger_post.subject %>
    </div>
    <div class="description-box content">
      <%= Kramdown::Document.new(ledger_post.content).to_html.html_safe -%>
    </div>
  <% end %>
  <%= timestamp_html(ledger_post) %>
  <% # Show groups, replies both up and down, with links and unapproved flags.
    my_replies = LinkReply.where(
      prior_post_id: ledger_post.original_version_id,
      deleted: false).order(created_at: :asc)
    my_replies_count = my_replies.count
    replied_to = LinkReply.where(
      reply_post_id: ledger_post.original_version_id,
      deleted: false).order(created_at: :asc)
    replied_to_count = replied_to.count
    my_groups = LinkGroupContent.where(
      content_id: ledger_post.original_version_id,
      deleted: false).order(created_at: :asc)
    my_groups_count = my_groups.count
    comma_needed = false # For separating group, reply, quotes sections.
    if my_groups_count > 0 || my_replies_count > 0 || replied_to_count > 0 %>
      <BR>
      <% if replied_to_count > 0 %>
        <%= "#{replied_to_count} #{'quote'.pluralize(replied_to_count)}" %>:
        <% replied_to.each do |a_reply_link|
          reply_post = a_reply_link&.prior_post&.latest_version %>
          <%= if reply_post
          link_to "##{a_reply_link.prior_post_id}",
            ledger_post_path(reply_post), title: "#{reply_post}"
          else # Post is missing or really deleted.
            "##{a_reply_link.prior_post_id}"
          end %><% # Add "unapproved" after the quote number if not approved.
          if !a_reply_link.approved_child || !a_reply_link.approved_parent
            %>-<%= link_to "unapproved", link_base_path(a_reply_link),
            class: "unapproved-link" %><%
          end
        end # replied_to.each
        comma_needed = true 
      end # if replied_to_count
      %><%
      if my_replies_count > 0
      %><% if comma_needed %>,<% end %>
        <%= "#{my_replies_count} #{'reply'.pluralize(my_replies_count)}:" %>
        <% my_replies.each do |a_reply_link|
          reply_post = a_reply_link&.reply_post&.latest_version %>
          <%= if reply_post
            link_to "##{a_reply_link.reply_post_id}",
              ledger_post_path(reply_post), title: "#{reply_post}"
            else
              "##{a_reply_link.reply_post_id}"
            end %><% # Add "unapproved" after the reply number if not approved.
          if !a_reply_link.approved_child || !a_reply_link.approved_parent
            %>-<%= link_to "unapproved", link_base_path(a_reply_link),
            class: "unapproved-link" %><%
          end
        end # my_replies.each
        comma_needed = true 
      end # if my_replies_count
      %><%
      if my_groups_count > 0
      %><% if comma_needed %>,<% end %>
        <%= "#{my_groups_count} #{'group'.pluralize(my_groups_count)}:" %>
        <% my_groups.each do |a_group_link|
          my_group = a_group_link&.group&.latest_version %>
          <%= if my_group
            link_to "##{a_group_link.group_id}", ledger_group_path(my_group),
              title: "#{my_group}"
          else # Record doesn't exist.
            "##{a_group_link.group_id}"
          end %><% # Add "unapproved" after the group number if not approved.
          if !a_group_link.approved_child || !a_group_link.approved_parent
              %>-<%= link_to "unapproved", link_base_path(a_group_link),
              class: "unapproved-link" %><%
          end
        end # my_groups.each
        comma_needed = true 
      end # if my_groups_count
      %>
  <% end # if any replies or groups
  %>
<% end # allowed_to_view
%>

app/views/ledger_posts/_ledger_post_with_small_buttons.html.erb
<li id="ledger-post-<%= ledger_post.id %>" class="row">
<% if !ledger_post.allowed_to_view?(current_ledger_user) %>
  <div class="col-xs-12 not-allowed-to-view">
    <%= "#{ledger_post.base_s} You don't have permission to view this object." %>
  </div>
<% else %>
  <div class="col-xs-3 col-sm-2 col-md-2 col-lg-1">
    <%= # Note we are showing the creator of this particular version of the
     # post, not the original or current creator.
     link_to gravatar_for(ledger_post.creator.user, size: 50),
      ledger_post.creator.user %>
    <span class="user"><%= link_to ledger_post.creator.name,
      ledger_post.creator.user %></span>
  </div>
  <div class="col-xs-9 col-sm-7 col-md-7 col-lg-9">
    <%= render "ledger_posts/ledger_just_the_post",
      { ledger_post: ledger_post } %>
  </div>
  <div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
    <%= button_to "Details", ledger_post_path(ledger_post),
        method: :get, class: 'btn btn-default button-full-width' %><br>
    <%= button_to "Reply", reply_ledger_post_path(ledger_post),
        method: :get, class: 'btn btn-default button-full-width' %><br>
    <% if ledger_post.creator_owner?(current_ledger_user) %>
      <%= button_to "Edit", edit_ledger_post_path(ledger_post),
        method: :get, class: 'btn btn-success button-full-width' %><br>
    <% end %>
    <%= render 'shared/ledger_delete_button',
      { ledger_object: ledger_post } %>
  </div>
<% end %>
</li>

app/views/ledger_posts/_name_content_form.html.erb
<%= form_with(model: @ledger_object, scope: :ledger_post,
  url: ledger_post_path, local: true, class: "form-group") do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control' %>
      <div class="description-form-box">
        <%= f.submit "Update Preview", name: "preview",
          class: "btn btn-primary float-right" %>
        <%= Kramdown::Document.new(@ledger_object.content)
          .to_html.html_safe -%>
      </div>

      <%= f.submit yield(:button_text), class: "btn btn-primary button-full-width" %>
<% end %>

app/views/ledger_posts/quotes.html.erb
<% provide(:page_title,
  "Quotes of ##{@ledger_object.id} #{@ledger_object.subject}") %>
<h1>List of Approved Quotes of <%= link_to "##{@ledger_object.id} #{@ledger_object.subject}",
  @ledger_object %></h1>

<%== pagy_bootstrap_nav(@pagy) %>

<% @ledger_objects.each do |an_object| %>
<%= render an_object %>
<% end %>

<%== pagy_bootstrap_nav(@pagy) %>

app/views/ledger_posts/show.html.erb
<% provide(:page_title, "Post ##{@ledger_object.id} #{@ledger_object.subject}") %>
<h1>Post #<%= @ledger_object.id %> <I>"<%= @ledger_object.subject %>"</I></h1>
<% if !@ledger_object.allowed_to_view?(current_ledger_user) %>
  <div class="not-allowed-to-view">
    <%= "#{@ledger_object.base_s} You don't have permission to view this object." %>
  </div>
<% else %>
  <%= render 'ledger_posts/ledger_post_plain',
    { ledger_post: @ledger_object } %>
  <p><%=
    # Update points since they're being shown.  Affects expiry time too.
    points_object = @ledger_object.update_current_points
    points_html(points_object) %>&nbsp; Created by <%=
    latestCreator = @ledger_object.creator.latest_version # Want latest name.
    link_to latestCreator.name, latestCreator.user,
      title: "View user's page." %>, <%=
    render 'ledger_bases/timestamp_and_expiry',
      { ledger_object: @ledger_object }
    %><%
    # Show groups, replies, quotes (even unapproved ones), with links and
    # approved flags.
    my_replies = LinkReply.where(
      prior_post_id: @ledger_object.original_version_id,
      deleted: false).order(created_at: :asc)
    my_replies_count = my_replies.count
    quoted_by = LinkReply.where(
      reply_post_id: @ledger_object.original_version_id,
      deleted: false).order(created_at: :asc)
    quoted_by_count = quoted_by.count
    my_groups = LinkGroupContent.where(
      content_id: @ledger_object.original_version_id,
      deleted: false).order(created_at: :asc)
    my_groups_count = my_groups.count
    comma_needed = false # For separating group, reply, quotes sections.
    if my_groups_count > 0 || my_replies_count > 0 || quoted_by_count > 0
      %>    <br><%
      if quoted_by_count > 0 %>
        <%= "#{quoted_by_count} #{'quote'.pluralize(quoted_by_count)}:" %><%
        quoted_by.each do |a_reply_link|
          reply_post = a_reply_link&.prior_post&.latest_version %>
          <%= if reply_post
            link_to "##{reply_post.id} (#{reply_post.creator.latest_version.name})",
              ledger_post_path(reply_post), title: reply_post.subject
          else # Post is missing or really deleted.
            "##{a_reply_link.prior_post_id}"
          end %><% # Add "unapproved" after the quote number if not approved.
          if !a_reply_link.approved_child || !a_reply_link.approved_parent
            %>-<%= link_to "unapproved", link_base_path(a_reply_link),
            class: "unapproved-link" %><%
          end
        end # quoted_by.each
        comma_needed = true
      end # if quoted_by_count
      %><%
      if my_replies_count > 0
      %><% if comma_needed %>,<% end %>
        <%= "#{my_replies_count} #{'reply'.pluralize(my_replies_count)}:" %><%
        my_replies.each do |a_reply_link|
          reply_post = a_reply_link&.reply_post&.latest_version %>
          <%= if reply_post
            link_to "##{reply_post.id} (#{reply_post.creator.latest_version.name})",
              ledger_post_path(reply_post), title: "#{reply_post.subject}"
            else
              "##{a_reply_link.reply_post_id}"
            end %><% # Add "unapproved" after the reply number if not approved.
          if !a_reply_link.approved_child || !a_reply_link.approved_parent
            %>-<%= link_to "unapproved", link_base_path(a_reply_link),
            class: "unapproved-link" %><%
          end
        end # my_replies.each
        comma_needed = true
      end # if my_replies_count
      %><%
      if my_groups_count > 0
      %><% if comma_needed %>,<% end %>
        <%= "#{my_groups_count} #{'group'.pluralize(my_groups_count)}:" %><%
        my_groups.each do |a_group_link|
          my_group = a_group_link&.group&.latest_version %>
          <%= if my_group
            link_to "##{my_group.original_version_id} (#{my_group.name})",
              ledger_group_path(my_group.original_version)
          else # Record doesn't exist.
            "##{a_group_link.group_id}"
          end %><% # Add "unapproved" after the group number if not approved.
          if !a_group_link.approved_child || !a_group_link.approved_parent
              %>-<%= link_to "unapproved", link_base_path(a_group_link),
              class: "unapproved-link" %><%
          end
        end # my_groups.each
        comma_needed = true
      end # if my_groups_count
      %><%
    end # if any replies or groups
  %>
  </p>
  <div class="row">
    <div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
      <%= # Note that rather than button_to(), which doesn't work with HTML 3
        # (it generates a HTML 5 <button> rather than a <input type="submit">),
        # so use an explicit form and submit button.
        form_with(url: reply_ledger_post_path(@ledger_object),
          local: true, method: :get) do |f| %>
        <%= f.submit "Reply",
          class: "btn btn-default button-full-width" %>
      <% end %><br>
    </div>
    <div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
      <%= form_with(url: quote_ledger_post_path(@ledger_object),
        local: true, method: :get) do |f| %>
        <%= f.submit "Quote",
          class: "btn btn-default button-full-width" %>
      <% end %><br>
    </div>
    <div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
      <%= form_with(url: replies_ledger_post_path(@ledger_object),
          local: true, method: :get) do |f| %>
        <%= f.submit "List Replies",
          class: "btn btn-default button-full-width" %>
      <% end %><br>
    </div>
    <div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
      <%= form_with(url: quotes_ledger_post_path(@ledger_object),
        local: true, method: :get) do |f| %>
        <%= f.submit "List Quotes",
          class: "btn btn-default button-full-width" %>
      <% end %><br>
    </div>
    <div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
      <%= form_with(url: descendants_ledger_post_path(@ledger_object),
          local: true, method: :get) do |f| %>
        <%= f.submit "Tree of Replies",
          class: "btn btn-default button-full-width" %>
      <% end %><br>
    </div>
    <div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
      <%= form_with(url: ancestors_ledger_post_path(@ledger_object),
          local: true, method: :get) do |f| %>
        <%= f.submit "Tree of Quotes",
          class: "btn btn-default button-full-width" %>
      <% end %><br>
    </div>
    <div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
      <%= form_with(url: descentors_ledger_post_path(@ledger_object),
          local: true, method: :get) do |f| %>
        <%= f.submit "Tree of Quotes and Replies",
          class: "btn btn-default button-full-width" %>
      <% end %><br>
    </div>
    <div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
      <%= form_with(url: ledger_base_path(@ledger_object),
          local: true, method: :get) do |f| %>
        <%= f.submit "Raw Details",
          class: "btn btn-default button-full-width" %>
      <% end %><br>
    </div>
    <% if @ledger_object.creator_owner?(current_ledger_user) %>
      <div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
        <%= form_with(url: edit_ledger_post_path(@ledger_object),
          local: true, method: :get) do |f| %>
          <%= f.submit "Edit",
            class: "btn btn-default button-full-width" %>
        <% end %><br>
      </div>
      <div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
        <%= render 'shared/ledger_delete_button',
          { ledger_object: @ledger_object } %>
      </div>
    <% end %>
  </div>
  <% # List all versions of the post, including the summary of changes text.
    ledger_objects = @ledger_object.all_versions
    if ledger_objects.count >= 2 %>
      <hr>
      <h2>All Versions of <%= @ledger_object.base_s %></h2>
      <ul class="list-ledger-objects">
        <% ledger_objects.each do |an_object| %>
          <li id="ledger-post-<%= an_object.id %>"><%=
            render 'ledger_posts/ledger_post_plain',
              { ledger_post: an_object } -%>
            <p>Created: <%=
            render 'ledger_bases/timestamp_and_expiry',
              { ledger_object: an_object }
            -%><%
            unless an_object.summary_of_changes.empty? %>              <BR>
              Summary: <%= an_object.summary_of_changes
            %><% end
            %></p>
          </li>
        <% end %>
      </ul>
  <% end %>
<% end %>